# Generated by Django 4.1.2 on 2023-06-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0002_company_remove_user_avatar_user_age_user_birth_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
    ]
