# Generated by Django 4.1.2 on 2023-06-14 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_remove_user_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="register_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
