# Generated by Django 4.1.2 on 2023-06-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_readinglesson_created_at_videolesson_created_at"),
        ("profiles", "0006_completedlesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedlesson",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
            preserve_default=False,
        ),
    ]
