# Generated by Django 4.1.2 on 2023-06-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="user",
        ),
        migrations.DeleteModel(
            name="CourseProgression",
        ),
        migrations.DeleteModel(
            name="UserAnswer",
        ),
    ]
