# Generated by Django 4.1.2 on 2023-06-14 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                            ("expert", "Expert"),
                        ],
                        max_length=150,
                    ),
                ),
                ("employees_limit", models.IntegerField()),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.subscriptiontype",
                    ),
                ),
            ],
        ),
    ]
